database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/bankmanager
  user: postgres
  password: root
  min: 2
  max: 100
  autocommit: true
  timeout: 5
cashback:
  delay: 0
  period: 30
  percent: 1
  test: false